spring.jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      dialect: 'org.hibernate.dialect.H2Dialect'
    hibernate.search:
      indexing_strategy : manual
      default_backend: elasticsearch1
      backends:
        elasticsearch1:
          type: elasticsearch
          host: http://localhost:9200
          discovery.enabled: true
          analysis_configurer: 'org.hibernate.search.integrationtest.fullstack.library.analysis.LibraryAnalysisConfigurer'
          index_defaults:
            lifecycle.strategy: drop-and-create-and-drop
            lifecycle.required_status: yellow
            #TODO HSEARCH-3316 remove 'refresh_after_write' and replace it with proper in-transaction code setting a completion handler:
            refresh_after_write: true
          log.json_pretty_printing: true

spring.datasource:
  driver-class: 'org.h2.Driver'
  url: 'jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
  username: 'sa'
  password: 'sa'

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.search.batchindexing: INFO