spring.jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      dialect: 'org.hibernate.dialect.H2Dialect'
    hibernate.search:
      default:
        directory_provider: local-heap

spring.datasource:
  driver-class: 'org.h2.Driver'
  url: 'jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1'
  username: 'sa'
  password: 'sa'

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.search.batchindexing: INFO