spring.datasource:
  url: jdbc:hsqldb:mem:dataplatformage
  driver-class: org.hsqldb.jdbcDriver
  username: sa
  password:

spring.jpa.properties:
  hibernate:
    dialect: org.hibernate.dialect.HSQLDialect
    hbm2ddl:
      auto: create-drop

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate: INFO